[package]
name = "workout_ffi"
version = "0.1.0"
authors = ["Thorsten Lorenz <thlorenz@gmx.de>"]
edition = "2018"

[lib]
name = "workout_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
workout = { path = "../workout" }
